<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVa5xrjx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVa5xrjx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVa5xrjx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVa5xrjx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVa5xrjx\appProdProjectContainer([
    'container.build_hash' => 'Va5xrjx',
    'container.build_id' => '02098e15',
    'container.build_time' => 1558079056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVa5xrjx');
